### ISSUE TITLE
wrong position with better combat mod

### ISSUE THREAD

**Issue by agir-a** [Globox1997/BackSlot#100]
![Screenshot (234)](https://user-images.githubusercontent.com/103606600/219878699-2bc63e67-870a-40a5-ad2f-78d179bfdf17.png)

**Comment by Globox1997** [comment]
This can be fixed via a resource pack

**Comment by agir-a** [comment]
ahh thanks!!

**Comment by ShadowSlayerFX1** [comment]
which resource pack?
