### ISSUE TITLE
Too large weapons 1.18.2

### ISSUE THREAD

**Issue by Ram3454** [Globox1997/BackSlot#101]
When I’m using my weapon and put it on my back, the model becomes overly large for no apparent reason. It was fine before hand, but now I don’t know why it’s doing this, the version is 1.18.2, I checked the config, but for modded weapons its too large

**Comment by Globox1997** [comment]
Not sure if this got already added on the 1.18.2 version but positioning and size can get adjusted via a resource pack, check out the readme.
