### ISSUE TITLE
The slot and the actual place where the item gets place are one off!

### ISSUE THREAD

**Issue by marian-mdn12** [Globox1997/BackSlot#102]
Was making this mod pack of around 290 mods and I realized that Artifacts and BackSlot are placed on top of each other.
I played a little with the slots for a good new location, but when I restarted the game the items are not in the places where they should be, they are off!
![image](https://user-images.githubusercontent.com/62489977/224506503-4caeac90-173d-42b7-a80b-3f2d2c16b5e6.png)
Now, if I look at the places where the items are they are off by -18 and 18, where the other slots should have been. 

Edit: I realized that I can activate the "change slot arrangement" and put them next to each other, but even then they don't stay in the exact slot and are one off!
![image](https://user-images.githubusercontent.com/62489977/224507979-602b04f0-c0bb-4638-8385-28ba0fb2986b.png)
 I know that I can just swap places but I want, if possible, the weapon to be in the weapon slot and otherwise, not be swapped. (I pay attention to details)

**Comment by Globox1997** [comment]
Should be fixed with a later version.
