### ISSUE TITLE
Oddly Oriented Visual Enchantment Weapons

### ISSUE THREAD

**Issue by CKuxixx** [Globox1997/BackSlot#106]
![image](https://user-images.githubusercontent.com/130175073/230673630-a317a498-e153-4d55-b7b2-14ec65cf5b30.png)

All weapons effected by the visual enchantments texture pack are oriented sideways instead of diagonally. (All normal weapons are fine.)

![image](https://user-images.githubusercontent.com/130175073/230673832-a7529e64-9d39-44de-90ac-da698f88458a.png)

I ran across an issue post that described a similar issue with the weapons from MCD Weapons. It said that later versions fixed this, but that was 2 years ago and I'm playing the later versions. If it's any help I used a custom Curseforge profile instead of installing fabric myself.

**Comment by Globox1997** [comment]
Positioning and size can get adjusted with a resource pack, check out the readme.
Resourcepacks of mods or standalone have an impact too.
