### ISSUE TITLE
wrong weapons  position 

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Globox1997/BackSlot#108]
you said that This can be fixed via a resource pack
but which resource pack and where cen i get it?

![219878699-2bc63e67-870a-40a5-ad2f-78d179bfdf17](https://user-images.githubusercontent.com/80198511/234500318-d1fa5b19-f875-4f4b-8a93-2424364a4401.png)

**Comment by therealgoat6** [comment]
I am having the same problem, figure it out yet?

**Comment by VybeX** [comment]
apparently, depending on whatever resource packs that's enabled in your game, you would have to remove each resource pack 1 by 1 and refresh them to see which pack is causing the items to float. in my case i use Alacrity and after i disabled it, the items on my character rendered properly. the bigger question is, how to fix this problem once you have figured out which resource pack causes it.

**Comment by Globox1997** [comment]
Check the other issues about rendering issues

**Comment by Globox1997** [comment]
Position and size of items can get adjusted with a resource pack, check out the readme.
