### ISSUE TITLE
weird 4th vs 1st hotbar slot ambiguity w/ belt slot

### ISSUE THREAD

**Issue by patpuck** [Globox1997/BackSlot#109]
this is my first time using backslot, so I'm not sure how exactly this is supposed to look, but it'd be neat if this 4th inventory slot feature would be configurable (especially since it's... y'know, not working)

putting something in the first inventory slot via the inventory directly will make a ghost copy of it in the fourth slot, and it can only be removed if you directly remove that same item from your first slot *in the inventory,* not including dropping it or whatever, or by putting a sword or something in the belt slot then taking it back out.

below is a video of this bug in action (this always happens to everyone on the server) and our modlist

https://github.com/Globox1997/BackSlot/assets/114644845/9568152e-6818-4439-9b43-334f7043bbe2
![MultiMC_6lbUtZ6bzT](https://github.com/Globox1997/BackSlot/assets/114644845/8e6bf4fc-4030-4ae1-a3c5-b491e27f64a8)
![MultiMC_iCY1gdpwGG](https://github.com/Globox1997/BackSlot/assets/114644845/89fb8dd2-56f0-4fa2-bdcd-12803bf1a928)

**Comment by Globox1997** [comment]
Lol this is supper odd. There should be no slot in the creative inventory.
Try with only backslot and its dependencies.

**Comment by patpuck** [comment]
chopped up the pack and found out it has to do with...Requiem? both of these are updated to their most recent versions, and I'm surprised nobody else has reported this issue.
I initially thought it had to do with Requiem's integrated dependency "Player Action Library" since that was the only feature of Requiem that sounded correlated, but running with just PAL instead of Requiem didn't cause the bug.
this is the minimum list that needs to be enabled to make this bug happen:
![MultiMC_PAymzArXCc](https://github.com/Globox1997/BackSlot/assets/114644845/e2b5ada0-40d9-416f-802c-4598c46b3a28)

**Comment by patpuck** [comment]
I've hit ladysnake up about it but I've never seen their support team respond to non-crash issues before, so I'm hoping for the best.
![image](https://github.com/Globox1997/BackSlot/assets/114644845/4a4cd5fb-b431-4476-94f7-a0e36da16e9f)

**Comment by Globox1997** [comment]
Reopen this still issue if Requiem devs provide some info? :D
