### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Chiromaw** [Globox1997/BackSlot#11]
would it be too hard to create a forge version of this mod for 1.12.2 (or at least the current version).  It would make a huge difference for mods that have many different tools and weapons you need to carry around with you like the Betweenlands (forge 1.12.2); while also looking better than just a simple quick inventory access.  I'm a forge user so I can't use this mod (yet?), but regardless, it looks fantastic and more preferable to back tools.  Great job

**Comment by Globox1997** [comment]
Thank you very much but I don't have plans to port it to forge since I'm a fabric exclusive modder.
