### ISSUE TITLE
Incompatibility with Universal Graves

### ISSUE THREAD

**Issue by Patbox** [Globox1997/BackSlot#111]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.2.13

### Describe the Issue

After some testing, if player has full inventory items aren't added to grave. This is caused by https://github.com/Globox1997/BackSlot/blob/1.20/src/main/java/net/backslot/mixin/compat/OnDeathItemDropCompatibility.java mixin being applied even when it shouldn't.

This breaks compatibility with Universal Graves, as removing it fixes the issue.

### latest.log

Not requred.

### Do you use any other mods except the required ones?

Universal Graves

**Comment by Globox1997** [comment]
Seems like I messed up the mixin plugin.
Fixed with [https://github.com/Globox1997/BackSlot/commit/5c72240db5dc5c5bcdb3f4978f2b5318e725902e](https://github.com/Globox1997/BackSlot/commit/5c72240db5dc5c5bcdb3f4978f2b5318e725902e)
