### ISSUE TITLE
Model not rendering properly

### ISSUE THREAD

**Issue by SilverMantis** [Globox1997/BackSlot#112]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.2.11.1

### Describe the Issue

The backslot items seem to be enlarged several times and are behind the position in which they are supposed to be in by about half a block, I have all resource packs turned off btw

### latest.log

![image](https://github.com/Globox1997/BackSlot/assets/140647107/0443a361-ff6c-4d44-b5e3-18d3ccfdbd36)

### Do you use any other mods except the required ones?

this issue seems to only occur with these ones

**Comment by Globox1997** [comment]
Position and size can get adjusted with a resource pack, check out the readme.
Resourcepack of mods and standalone have an impact too if they are adjusting any of these.
