### ISSUE TITLE
Crossbows do not render on back properly.

### ISSUE THREAD

**Issue by DelphiDv** [Globox1997/BackSlot#113]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

backslot-1.2.11.1

### Describe the Issue

![image](https://github.com/Globox1997/BackSlot/assets/28810353/27f1bd5a-e6a0-4f47-aea5-2449e634730f)
I've looked at other issues here describing similar problem, however none of the answer helps me.

### latest.log

[latest.log](https://github.com/Globox1997/BackSlot/files/12210232/latest.log)
probably not actually relevant, log i,mplies there are other mods but they're all disabled.

### Do you use any other mods except the required ones?

no

**Comment by DelphiDv** [comment]
The more mods i add the worse it gets, swords also dont render properly in either slot, not sure which mod is at fault tho.

**Comment by SilverMantis** [comment]
I'm having this exact glitch rn

**Comment by Globox1997** [comment]
Position and size can get adjusted with a resource pack, check out the readme.
Resourcepacks of mods and standalone have an impact on that too.

**Comment by stormingsilver** [comment]
If you are using a Vanilla Tweaks resource pack, don't enable "Item Stitching Fix" in the "Fixes and Consistency" dropdown; it  can cause this
