### ISSUE TITLE
[Compatibility Issue] BackSlot x Auto HUD

### ISSUE THREAD

**Issue by LazyBengie** [Globox1997/BackSlot#114]
_**Fabric**: 0.14.21, **BackSlot**: 1.2.11, **Auto HUD**: 4.3, **Version**: 1.19.2_
This mod and [Auto HUD](https://modrinth.com/mod/autohud) seem to be almost compatible, but not completely.

![github1](https://github.com/Globox1997/BackSlot/assets/141587039/456b2b9a-0b9c-4aa3-9b38-9f0d275e5846)
HUD raised
![github2](https://github.com/Globox1997/BackSlot/assets/141587039/6f857cfd-bc84-43fa-8c3a-173ade284a02)
HUD lowered

The HUD slots get hidden, but tools inside them don't.

**Comment by Globox1997** [comment]
Ask the AutoHud dev for compatibilty. Might be fixed with the latest version tho.
