### ISSUE TITLE
[Bug]: Pos change doesn't work correctly in 1.20.1

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/BackSlot#116]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

1.2.14

### Describe the Issue

Change Positions:
Backslot X 18
Backslot Y 36
Beltslot X 36
Beltslot Y 18

Background looks correct

Restart client

![image](https://github.com/Globox1997/BackSlot/assets/97298005/ca710f0b-bf7a-47c2-a4fb-8b276b5d6e0f)

Actual Icons & Slots are out of space

### latest.log

-

**Comment by Globox1997** [comment]
You need BackSlotX 18, BackSlotY 18, BeltSlotX 36, BeltSlotY 36 with the latest update.
