### ISSUE TITLE
[BUG] On minecraft start, keybinds are screwed

### ISSUE THREAD

**Issue by Merith-TK** [Globox1997/BackSlot#12]
I use my mouse for keybinds like so

Mouse5 = Side Slot
Shift+Mouse5 = Back Slot.

However whenever i restart minecraft, they are swapped, as if the mod doesnt actually register the order in which they are added

**Comment by Globox1997** [comment]
My mod page says: Try to install amecs if this happens [https://www.curseforge.com/minecraft/mc-mods/amecs](https://www.curseforge.com/minecraft/mc-mods/amecs)

**Comment by Merith-TK** [comment]
> My mod page says: Try to install amecs if this happens https://www.curseforge.com/minecraft/mc-mods/amecs

I installed it, the only difference, is that now they are both registered to `SHIFT+M5` so nothing really changed aside from having to go into the config and change one less value, (instead of rebinding both, i rebind the incorrect one)

**Comment by Globox1997** [comment]
mh, sounds more like a problem from the amecs side, may ask the dev

**Comment by Merith-TK** [comment]
> mh, sounds more like a problem from the amecs side, may ask the dev

I set BackSlot to Shift+M5,
And BeltSlot to M5,

Vanillia: Rebinds Both to M5
Amecs: Rebinds Both to SHIFT+M5

I even looked in the minecraft optionsof.txt file, they both register as M5 no matter what.

**Comment by Globox1997** [comment]
Reopen if still persistent in latest version.
