### ISSUE TITLE
Can't take item out with mouse from back

### ISSUE THREAD

**Issue by Akorian** [Globox1997/BackSlot#13]
I am using this mod and the mod artefacts which uses trinkets. Everything seems to work fine and as intended. BUT I can't take the item, I have on my back out of the slot via the inventory. I must use the bind. (also, why must I use a shift key bind? That kinda succs)
Compatibility with not enough animations would be also cool.

**Comment by Globox1997** [comment]
You have to change a config option for trinkets compatibility and any crash log with not enough animations?

**Comment by Akorian** [comment]
I didn't play long using NEA but it didn't crash. Just no animations when equipping a sword from the hip or back. 
My problem with the hud persists. I can't take a tool out from the slot on the back using my mouse. Only the shortcuts work. I reloaded and then restarted. But nothing did anything. 
```
{ 
	"backslot_scale": 2.0,
	"beltslot_scale": 2.0,
	"backslot_sounds": true,
	// Use for mod compatibility - Reload necessary
	"change_slot_arrangement": true,
	"disable_backslot_hud": true
}
```
Screenshots: https://imgur.com/a/JEGt8cy

**Comment by Globox1997** [comment]
Looks like the same bug as with [https://github.com/Globox1997/BackSlot/issues/10](https://github.com/Globox1997/BackSlot/issues/10)
