### ISSUE TITLE
Backslot Hud overlapping offhand slot

### ISSUE THREAD

**Issue by Crocwave** [Globox1997/BackSlot#130]
### Minecraft Version

1.20.x

### Mod Loader Version

Fabric 0.15.6

### Mod Version

1.2.15+1.20.1

### Describe the Issue

When I equip an item in my offhand and equip an item in my backslot, as shown in the screenshot below, the Hud
s overlap. This is most likely because the Backslot Hud is on the left side where the offhand is. I saw no way to change this in the config.

![Offhand overlap issue](https://github.com/Globox1997/BackSlot/assets/163483966/3dff0f1b-ef3e-40bb-8fd2-dfef91f9eb3a)

### latest.log

[latest.log](https://github.com/Globox1997/BackSlot/files/14609507/latest.log)

### Do you use any other mods except the required ones?

Nothing other than Cloth Config API and Fabric API (required). I am also running it on Modrinth Modloader.

**Comment by Felisinnn** [comment]
You can change the HUD slot x and y axis in the `backslot.json`. 
This is my hud config in case you want to copy it `
"hudSlotX": 240,"hudSlotY": 0,` 
![2024-07-28_20 26 13](https://github.com/user-attachments/assets/5924fe8a-e351-481e-b5fd-29e493b97207)

**Comment by Globox1997** [comment]
Yes this can be solved with the existing config options.
