### ISSUE TITLE
Small Tools in Hip Slot Positioned Incorrectly

### ISSUE THREAD

**Issue by SergeantFlavor** [Globox1997/BackSlot#132]
### Minecraft Version

1.21.x

### Mod Loader Version

0.15.11

### Mod Version

1.2.15

### Describe the Issue

Sheers and Flint & Steel do not position correctly on character model
![2024-07-12_12 17 08](https://github.com/user-attachments/assets/94e8bc66-7583-4578-8d9c-72685b117493)
![2024-07-12_12 17 17](https://github.com/user-attachments/assets/f84ee056-de47-4788-8765-3a977ff2f8c9)
![2024-07-12_12 22 23](https://github.com/user-attachments/assets/52979591-d2f8-47ed-8e1a-786680f652dd)
![2024-07-12_12 22 41](https://github.com/user-attachments/assets/e930846f-006c-43c3-845a-2208b2e7227a)

### latest.log

[latest.log](https://github.com/user-attachments/files/16197509/latest.log)

**Comment by tagrimo** [comment]
I've had this problem too for the entire time I've used this mod, since 1.16. I would love to see a fix.

**Comment by Globox1997** [comment]
Pls look though the issues or read the github readme, this is a common issue.
