### ISSUE TITLE
Conflict Crash with Medieval Weapons

### ISSUE THREAD

**Issue by Virusnest** [Globox1997/BackSlot#133]
### Minecraft Version

1.21.x

### Mod Loader Version

0.16.0

### Mod Version

1.2.15

### Describe the Issue

When using Medieval Weapons attempting to equip any item in the back slot valid or not the game will crash.
removing Medieval Weapons fixes this issue.

### latest.log

[https://mclo.gs/CfZ4SW0](https://mclo.gs/CfZ4SW0)

**Comment by Torathion** [comment]
Same crash here. Tried to equip a TieredZ iron sword onto the backslot and it crashed.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/BackSlot/commit/33192adf99caca5e9d0eef678abfd77a9eb0112b](https://github.com/Globox1997/BackSlot/commit/33192adf99caca5e9d0eef678abfd77a9eb0112b)
