### ISSUE TITLE
Add mace from 1.21 compatibility for backslot

### ISSUE THREAD

**Issue by Darealsharp** [Globox1997/BackSlot#134]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug/feature.

### Description of your suggestion.

Can you add a compatibility between the mace and the backslot mod but only in the "back slot" to be realistic.....

(Its bassicly a discord request send to github too)

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/BackSlot/commit/78816fc9ab62bbaec1fc423ee6f7e408476bfd78](https://github.com/Globox1997/BackSlot/commit/78816fc9ab62bbaec1fc423ee6f7e408476bfd78)
