### ISSUE TITLE
wrong positioning of few items from another mods (far from back and small)

### ISSUE THREAD

**Issue by Krizma7** [Globox1997/BackSlot#136]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-loader-0.15.11-1.20.1

### Mod Version

backslot-1.2.15

### Describe the Issue

Mod failed to position only few items from mods Archers RPG, Paladins and Priest RPG, Rogues and Warriors RPG
I have modpack Dungeon Heroes-1.9
I tried to make datapack and resource pack but it won't help.

![prtsc3](https://github.com/user-attachments/assets/6a89e392-3fab-4bc0-9f7d-aede6431ab2f)
![prtsc2](https://github.com/user-attachments/assets/019b7c8f-37bd-4db5-b837-99e83b18308f)
![prtsc1](https://github.com/user-attachments/assets/3b5f4ab8-f03c-469b-ad4a-6bdecb05be69)
![prtsc4](https://github.com/user-attachments/assets/122b8be3-73e0-4597-bc54-216910140aab)

### latest.log

[latest.log](https://github.com/user-attachments/files/17128992/latest.log)

**Comment by Globox1997** [comment]
Pls look through the issues or read the readme for this kind of issue.
