### ISSUE TITLE
Tool render doesn't scale with player render

### ISSUE THREAD

**Issue by CammiePone** [Globox1997/BackSlot#14]
Mods that resize the player (i.e. using Pehkui) don't have the tool render with the player's new scale.
![image](https://user-images.githubusercontent.com/16853086/109839798-7a1fe480-7c15-11eb-855d-0ae729352324.png)

**Comment by Globox1997** [comment]
I have no plans to make it compatible with those mods currently

**Comment by CammiePone** [comment]
It wouldn't be all that difficult. Turning it into a FeatureRenderer and injecting it into the PlayerEntityRenderer constructor after the 7th addFeature() call would automatically make it compatible ([re: Cam's Wearable Backpacks](https://github.com/CammiePone/Cam-s-Wearable-Backpacks/blob/master/src/main/java/dev/cammiescorner/camsbackpacks/core/mixin/PlayerEntityRendererMixin.java#L22-L26)).

**Comment by Globox1997** [comment]
I already inject at the tail of the PlayerEntityRenderer, so you are requesting to change the HeldItemFeatureRenderer to a FeatureRenderer?

**Comment by Globox1997** [comment]
Tested it with Pehkui and it works just fine...

**Comment by Globox1997** [comment]
Reopen if still not working :)
