### ISSUE TITLE
Compatibility with item sorting and trinkets mods

### ISSUE THREAD

**Issue by Kelavus** [Globox1997/BackSlot#15]
You cant have all these mods together, wherever you put the backslot slot in the inventory. Making a config option where the slots go above where the one gauntlet slot is would fix this issue.

**Comment by Globox1997** [comment]
Can you show me a screenshot where the slots should go?

**Comment by evstarMC** [comment]
Hey @Globox1997
Yeah this seems to be the issue I was having too. I'm not sure what causes it, perhaps a dependency or something. 
Toggling the changeArrangement compatibility setting in the config to true fixed the issue for a bit, however, after adding more mods it kept breaking again. Basically, the InventoryScreenMixin would disregard that I had set the compatibility setting to true and the background textures would be default position while the actual slot interfaces from PlayerScreenHandlerMixin would be in the in the compatibility arrangement positions.

I was able to fix these compatibility issues by changing the backSlot_y and beltSlot_y values to -18 in both the InventoryScreenMixin & PlayerScreenHandlerMixin and disabling the changeArrangement compatibility config setting. Works like a charm now: 

![image](https://user-images.githubusercontent.com/82483172/116617156-8a012f80-a90b-11eb-92e4-75ff29eb2d69.png)

**Comment by Globox1997** [comment]
It is basically not an option to just put the slots higher, shown in this screenshot because mods which use the trinkets api can basically use all three spaces next to the playermodel, just depends on which mods you have installed. that's the reason for the arrangement config

**Comment by Globox1997** [comment]
I think a good solution will be a config option to move the positions manually - as you did @evstarMC 
Added with [https://github.com/Globox1997/BackSlot/commit/2be53542f4c5661c9aa0f62ca2ead97e6a1e01af](https://github.com/Globox1997/BackSlot/commit/2be53542f4c5661c9aa0f62ca2ead97e6a1e01af)
