### ISSUE TITLE
More documentation.

### ISSUE THREAD

**Issue by AmyMialee** [Globox1997/BackSlot#17]
It would be nice to know more about how this mod works and how to change the way items are displayed/which items can be put in which slots.

**Comment by Globox1997** [comment]
Probably a good idea but except for which item can get into the slots, it should be pretty much self explaining.
On the modpage there is already a short description which items can get placed into the slots :)

**Comment by AmyMialee** [comment]
this isn't about what currently exists, this is for the sake of mods that
want to be compatible.
I have a mod I'd like to make compatible, and I have 3 items I'd like on
the back slot and 1 for the beltslot.

**Comment by Globox1997** [comment]
So basically Backslot uses a method to check if the item instance is allowed, so every item instance of the list on the modpage can get put in the slot without extra work :) 
Most people don't read the mod page so I have no plans to edit/add the compatible items text on it.
You could make a PR for the items if they are not instances of the existing ones under network/SwitchPacket method isItemAllowed :) 
Slot 41 is the backslot and 42 is for the belt

**Comment by AmyMialee** [comment]
the main issue is with displaying them correctly, one of my items when put
in the back slot ends up impaling the player :P

**Comment by Globox1997** [comment]
There are two ways to fix this:
Change the position of the third person item in your model json
I have to manually check the item in code and change the position

**Comment by Globox1997** [comment]
I think the Readme covers enough information.
