### ISSUE TITLE
[Request]: Shields on Back Slot

### ISSUE THREAD

**Issue by VinnyStalck** [Globox1997/BackSlot#18]
When playing Skyrim one of my must have mods is one that makes the shields render in the player's back, and I think it would be awesome to be able to do this with this mod.

![image](https://user-images.githubusercontent.com/42945819/121903028-69543400-cd17-11eb-8e9f-4b26f32c99e4.png)

**Comment by Globox1997** [comment]
this feature is requested multiple times already but I have to give the same answer:
since the vanilla mc shield (or basically the player model arms) is unproportionally, the handlebar of the shield will stick inside the body of the player which looks odd

**Comment by Globox1997** [comment]
Added a setting to the addon [https://github.com/Globox1997/BackSlotAddon/commit/83f8beb85b360cd35f356e03bd8ff00e3f98231d](https://github.com/Globox1997/BackSlotAddon/commit/83f8beb85b360cd35f356e03bd8ff00e3f98231d)
