### ISSUE TITLE
Crash with MC Dungeons Weapons when any weapon or tool is placed into Belt Slot when MCDW is loaded alongside BackSlot

### ISSUE THREAD

**Issue by chronosacaria** [Globox1997/BackSlot#19]
I separated out Soul Daggers into their own base (so now they are chronosacaria.mcdw.bases.McdwSoulDagger rather than chronosacaria.mcdw.weapons.SoulDaggers) and I forgot to mention this to you when I did this. 

Unfortunately, when they are put into the belt slot, they cause a crash. I've attached the crash report that was created. It seems to happen regardless of what item is put into the belt slot. Everything seems fine in the back slot.

[crash-2021-06-16_09.37.42-client.txt](https://github.com/Globox1997/BackSlot/files/6663462/crash-2021-06-16_09.37.42-client.txt)

**Comment by Globox1997** [comment]
[backslot-1.1.13.zip](https://github.com/Globox1997/BackSlot/files/6697058/backslot-1.1.13.zip)
could you test this please? :) you have to unzip the file

**Comment by Globox1997** [comment]
Tested it and fixed with [https://github.com/Globox1997/BackSlot/commit/e392d76cfcff817e537195e777e16bc1885acf6b](https://github.com/Globox1997/BackSlot/commit/e392d76cfcff817e537195e777e16bc1885acf6b)
