### ISSUE TITLE
The hotkey changed after restart the game

### ISSUE THREAD

**Issue by eslym** [Globox1997/BackSlot#2]
I set the back slot hotkey to `z` and belt slot hotkey to `x`, but every time i restart the game the belt slot hotkey will be added by a shift key and became `shift + x`, even its only have x key in `options.txt`
![image](https://user-images.githubusercontent.com/3667594/95061883-c7fbf380-072e-11eb-9465-9a81d5874716.png)
![image](https://user-images.githubusercontent.com/3667594/95061945-df3ae100-072e-11eb-8eb6-c62be85e18cc.png)

**Comment by Globox1997** [comment]
since I'm using the amecs api, I'll ask the mod dev how to fix this ;)

**Comment by Globox1997** [comment]
Can't reproduce the bug, probably a mot incompatibility. You can check it with only installing this mod and nothing else

**Comment by eslym** [comment]
Problem even exists when this is the only mod installed, step to reproduce:
1. change the belt hotkey to any key without shift modifier (example: `x`)
2. close the game (close it completely, not return to title)
3. start the game and the hotkey will become with modifier shift (example: `shift + x`)

**Comment by Globox1997** [comment]
Followed your instructions and key doesn't change. Which version do you play on?

**Comment by eslym** [comment]
Minecraft 1.16.3
Fabric 0.9.3+build207

**Comment by eslym** [comment]
ok, the problem solved after i added amecs into mods, its required but not mentioned in description

**Comment by Globox1997** [comment]
Mh at least that fixed it for you :) otherwise it is already implemented so no need for extra downloading it
