### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Eillo3o** [Globox1997/BackSlot#21]
The only other files I have in my mods folder are optifabric, optifine and fabric api.

![dfdfdfdffd](https://user-images.githubusercontent.com/86573709/123558810-3d4ca000-d766-11eb-9f61-017a6122caba.PNG)

[crash-2021-06-27_16.33.45-client.txt](https://github.com/Globox1997/BackSlot/files/6722273/crash-2021-06-27_16.33.45-client.txt)

**Comment by Eillo3o** [comment]
I tested this with other mods, and i believe it was an issue on my end. oops.

**Comment by Globox1997** [comment]
You need cloth config as a dependency too :)
