### ISSUE TITLE
Mending doesn't apply to backslot tools

### ISSUE THREAD

**Issue by VoxanyNet** [Globox1997/BackSlot#22]
It would be awesome if mending worked on tools that are equipped in either backslot.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/BackSlot/commit/2e725550a5a58cd4bccb326b439d316955f985ca](https://github.com/Globox1997/BackSlot/commit/2e725550a5a58cd4bccb326b439d316955f985ca)
