### ISSUE TITLE
Inventory buy

### ISSUE THREAD

**Issue by Chargedx** [Globox1997/BackSlot#23]
The inventory slots are bugged in the inventory. How do I fix that?
![Screenshot 2021-07-27 113930](https://user-images.githubusercontent.com/88047434/127184141-bb1ef7b3-cfe9-444f-b6cd-7335acc03e1f.png)

**Comment by Globox1997** [comment]
Turn off the compatibility setting and set the positions of the slot by hand via config settings

**Comment by Chargedx** [comment]
Are you able to let me know what settings I need to put in because I have no clue lol.

**Comment by Globox1997** [comment]
you have to change backslot x and y to a position which fits your needs :)
You can play with it around but for full appliance you have to relog to your world

**Comment by Chargedx** [comment]
Ok. Would you have any suggestions￼ for the back slot positions?

**Comment by Chargedx** [comment]
I just did -18 on both the x and y back slots and nothing happened.

**Comment by Chargedx** [comment]
It didn't do anything
![Screenshot 2021-07-27 165358www](https://user-images.githubusercontent.com/88047434/127226067-8c279f9a-6c38-4347-b11c-48af188e721d.png)

**Comment by Chargedx** [comment]
Do you have anything to help with that?

**Comment by Globox1997** [comment]
Yes there is something not cleared out. You have to turn the compat setting to false for applying the advanced settings

**Comment by Chargedx** [comment]
So I turned the compat setting to false and I was able to move the back slots, but when I finished and exited out the world it messed up again and now I can't change the back slots.
![3](https://user-images.githubusercontent.com/88047434/127349015-95c7cb9a-0bab-46b3-9337-d1481baacf2a.png)
![NUMBER 2](https://user-images.githubusercontent.com/88047434/127349017-a1b45771-364c-4003-aeb8-de02afbe2ed2.png)

**Comment by Globox1997** [comment]
Ups forgot you have to turn the change slot arrangement setting to false to enable the advanced settings

**Comment by Chargedx** [comment]
Ok, that help and I was able to fix it. Thanks for the help:)

**Comment by L0oois** [comment]
> Yes there is something not cleared out. You have to turn the compat setting to false for applying the advanced settings

Compat settings? what is that and where do i find it, im having the same problem :C

**Comment by L0oois** [comment]
![2021-09-04_17 21 41](https://user-images.githubusercontent.com/87247529/132109518-59f17ccb-a31e-43f0-977e-96c85b06dc87.png)
