### ISSUE TITLE
Backslot Crashes on Startup!

### ISSUE THREAD

**Issue by Diycnel** [Globox1997/BackSlot#26]
I'm trying to get the mod to work but using just it and the Fabric API it seems to just crash on startup.
**Fabric Loader @version 0.11.6
Fabric API @version 0.38.2+ 1.17**

**Comment by Globox1997** [comment]
Tested it and it works for me, mh

**Comment by Globox1997** [comment]
Could you send the crash log here pls

**Comment by Diycnel** [comment]
[crash-2021-08-24_19.50.11-client.txt](https://github.com/Globox1997/BackSlot/files/7042682/crash-2021-08-24_19.50.11-client.txt)

**Comment by Globox1997** [comment]
Forgot something, you need cloth config installed too

**Comment by Diycnel** [comment]
Yeah, I fixed it!
