### ISSUE TITLE
Compatibility issue, doesn't work with some mod that use Trinket API 

### ISSUE THREAD

**Issue by manaheti1** [Globox1997/BackSlot#27]
Back slot is overleap by a Trinket slot
Can't take or put item with that slot, Use hotkey has no problem.
![image](https://user-images.githubusercontent.com/65333593/131247475-cad5de6b-f9d6-4499-8ed1-5ff48d76b0f1.png)

I think it conflict with one of these:
Extra Alchemy: https://github.com/zabi94/ExtraAlchemy/wiki
Void Totem: https://www.curseforge.com/minecraft/mc-mods/voidtotem-fabric
Things: https://github.com/glisco03/things

Here are my option
![image](https://user-images.githubusercontent.com/65333593/131247652-66ee5113-e17d-4157-a450-6bf3ce933d62.png)
![image](https://user-images.githubusercontent.com/65333593/131247672-3beaf827-31fa-49c8-bd76-5d4865f7f1c7.png)

If I change X,Y for back slot It just move the border not the actual slot.

**Comment by manaheti1** [comment]
Update. 
![image](https://user-images.githubusercontent.com/65333593/131248423-ae57843c-226c-4074-aab9-a7724f6cbe5c.png)
I uninstall Void Totem and Trinket of Undying while keeping the same setting. 
Back slot now stuck with Ring slot
Belt slot lost its border

**Comment by Globox1997** [comment]
You have to reload the world or even restart the client to make the changed slot seetings apply. If "change slot arrangement" is set to true, the slots switch to the right side of the inventory screen which make them accessible

**Comment by Globox1997** [comment]
This is fixed in a later version :) but slots still have to get arranged with the config
