### ISSUE TITLE
Sheathed items (back and hip slots) dissappear on death

### ISSUE THREAD

**Issue by BuizelKing** [Globox1997/BackSlot#28]
Upon dying ingame and picking up the totem of return, it restored all of my items but... I lost whatever was in my hip and back slots (a bow and axe). I couldnt find them in my inventory or on the ground

**Comment by Globox1997** [comment]
Which mod adds this totem item?

**Comment by BuizelKing** [comment]
Back Slot

**Comment by Globox1997** [comment]
You mixed something up, BackSlot doesn't add any items

**Comment by BuizelKing** [comment]
Oh yes! Sorry about that, totem is the Totem of Persevering from Charm!

**Comment by mtb-xt** [comment]
Same thing happened to me several times, items from the back and the belt disappear with the Totem of Preserving -_-

**Comment by Globox1997** [comment]
For reference, it happens here [https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/module/totem_of_preserving/TotemOfPreserving.java](https://github.com/svenhjol/Charm/blob/master/src/main/java/svenhjol/charm/module/totem_of_preserving/TotemOfPreserving.java)
