### ISSUE TITLE
[Feature Request] add support for Soulbound

### ISSUE THREAD

**Issue by elhertz** [Globox1997/BackSlot#29]
https://github.com/UpcraftLP/Soulbound

Current behavior: items in the backslot/beltslot with the soulbound enchantment will drop on the ground

Expected behavior: items in the backslot/beltslot with the soulbound enchantment stay in their slots

**Comment by Globox1997** [comment]
This fork isn't released on curseforge yet. I will add compat when it is

**Comment by Globox1997** [comment]
Have no plans to add compat from my side.
