### ISSUE TITLE
Backslot, Trinkets compat bug.

### ISSUE THREAD

**Issue by Cluelesshobo** [Globox1997/BackSlot#3]
Elytra's using the mod [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) and Backslot together makes elytra's no longer function.

Results:
The player will attempt to enter the elytra animation for a split second before reverting back to falling. This bug is not present with [Origins ](https://www.curseforge.com/minecraft/mc-mods/origins)mod dispite also using elytras on the player.

Potential Cause:
The _back slot_ may be conflicting with the _cape slot_ from trinkets in someway.

**Comment by Globox1997** [comment]
Thanks for noticing me, don't know if there will be a compat fix but now I'm aware of it

**Comment by Globox1997** [comment]
Can't reproduce this bug, may nothing to do with trinkets compat
