### ISSUE TITLE
When changing the positions of the slots this happends

### ISSUE THREAD

**Issue by ThebigTijn** [Globox1997/BackSlot#31]
![Captur](https://user-images.githubusercontent.com/85112325/135319354-0984d91f-4615-4c90-8ced-d7a7a285989c.PNG)

**Comment by Globox1997** [comment]
This looks like an older version of the backslot mod?

**Comment by Globox1997** [comment]
So the config screen told ya you have to restart the game to make the config apply?
My guess is the positions are just badly set

**Comment by ThebigTijn** [comment]
no because those are only trhe textures, the actual slots work fine.

**Comment by Globox1997** [comment]
it is still like that after restart? what are your settings?

**Comment by ThebigTijn** [comment]
![Cature](https://user-images.githubusercontent.com/85112325/135329193-756afea1-fc85-4322-8cf9-598ebbfa8e4e.PNG)
![Captue](https://user-images.githubusercontent.com/85112325/135329196-5d738449-5371-471f-9608-511aa46e0ffb.PNG)

**Comment by Globox1997** [comment]
Turn off the change slot arrangement setting and place them via the advanced settings

**Comment by ThebigTijn** [comment]
alr it worked now thanks!

**Comment by Globox1997** [comment]
You are welcome :)
