### ISSUE TITLE
[Suggestion] Compatibility with Infinitory mod

### ISSUE THREAD

**Issue by Furgl** [Globox1997/BackSlot#34]
[Infinitory](https://github.com/Furgl/Infinitory) is my mod that adds extra slots to the player's inventory dynamically. It does this by changing the indices of slots, which breaks compatibility with many inventory slot mods, including BackSlot. Unfortunately, there's not much I can do to fix this in Infinitory, but there should be a fairly simple fix that you can add to BackSlot, if you'd like:

Rather than using hardcoded slot indices, like in [`IngameHudMixin`](https://github.com/Globox1997/BackSlot/blob/cf37f9c63c69ded27c9450fa109c25fba7d66759/src/main/java/net/backslot/mixin/InGameHudMixin.java#L47), [`BackToolFeatureRenderer`](https://github.com/Globox1997/BackSlot/blob/cf37f9c63c69ded27c9450fa109c25fba7d66759/src/main/java/net/backslot/client/feature/BackToolFeatureRenderer.java#L47), and [`BeltSlotFeatureRenderer`](https://github.com/Globox1997/BackSlot/blob/cf37f9c63c69ded27c9450fa109c25fba7d66759/src/main/java/net/backslot/client/feature/BeltSlotFeatureRenderer.java#L36), you could store the slots that you add in [`PlayerScreenHandlerMixin`](https://github.com/Globox1997/BackSlot/blob/cf37f9c63c69ded27c9450fa109c25fba7d66759/src/main/java/net/backslot/mixin/PlayerScreenHandlerMixin.java#L49) and call `slot.getIndex()`

Since this compatibility issue is only caused by my mod, I completely understand if you don't want to make changes to your mod to fix it.

**Comment by Globox1997** [comment]
Sounds good, definitely open for a PR :)

**Comment by Globox1997** [comment]
I have no plans to add compatibility from my side. Reopen this issue if somebody is open to create a PR.
