### ISSUE TITLE
Odd or misplaced models MC dungeons weapons

### ISSUE THREAD

**Issue by CountSjorn52** [Globox1997/BackSlot#38]
Some of the models for the weapons are either too large of displayed incorrectly, like have a chainsaw sword that's bigger than you when sheathed and the butterfly crossbow just embedded into your back spear style, these are the broken sawblade, ancient sawblade, bubble burster bow and butterfly crossbow
![2021-10-30_08 37 45](https://user-images.githubusercontent.com/93433681/139533355-67d775bf-3236-4d27-b40c-e00f11aed822.png)

![2021-10-30_08 37 48](https://user-images.githubusercontent.com/93433681/139533267-d78dd434-2771-4d09-a8c6-6cbd35e051d0.png)
![2021-10-30_08 37 51](https://user-images.githubusercontent.com/93433681/139533268-bd47ba61-a41a-4449-b5e8-633bb3f11029.png)
![2021-10-30_08 41 30](https://user-images.githubusercontent.com/93433681/139533269-0c4343cd-5093-49d7-9d94-f214f48cf679.png)

**Comment by Globox1997** [comment]
Should be fixed with a later version

**Comment by Globox1997** [comment]
Position, translation and scale can get adjusted via resource packs as stated in README.
