### ISSUE TITLE
[1.16.3] Incompatibility with Gravestones, items are wiped

### ISSUE THREAD

**Issue by JuergenSchT** [Globox1997/BackSlot#4]
Fabric Loader: 0.10.6+build.214
Fabric API: 0.25.0+build.415
Whenever a player with items on the Back or Belt slots from this mod dies, the items in those slots disappear forever. They are not found on the grave, they are not dropped on the ground, they are lost forever. The items in those slots are shown in their proper place in the hotbar [like other items in the Vanilla slots] until the "respawn" button is used. Then, they can't be found on or around the place of death.
Modpack tested:
```
  [✔️] ;OpenJ9Compat
  [✔️] backslot-1.1.6
  [✔️] Fabric_API
  [✔️] gravestones-1.6
  [✔️] lithium-fabric-mc1.16.3-0.5.6
  [✔️] modmenu-1.14.6+build.31
  [✔️] phosphor-fabric-mc1.16.1-0.6.0+build.7
  [✔️] sodium-fabric-mc1.16.3-0.1.0
```
I also tried BackSlot 1.1.0 and Gravestones 1.5, and there was no difference in the bug.
The reason why I posted this issue here instead of Gravestones' repo is because I think this might be caused by BackSlot. Other mods incompatible with Gravestones, like mods using [Curios API](https://www.curseforge.com/minecraft/mc-mods/curios-fabric) don't have their items disappear on death, they are simply dropped on the floor, ignoring the grave.

**Comment by Globox1997** [comment]
My first intention is, it's a compat issue on the gravestones mod side

**Comment by Globox1997** [comment]
Added partly compat for gravestone, items will now drop instead of disappear[https://github.com/Globox1997/BackSlot/commit/1b32865cccf7a00530385553ec6015611a8c1001](https://github.com/Globox1997/BackSlot/commit/1b32865cccf7a00530385553ec6015611a8c1001)
