### ISSUE TITLE
Items kept in back slots don't get saved in gravestones put by UniversalGraves if Charm is installed

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Globox1997/BackSlot#40]
**MC** 1.17.1
**Fabric** loader 0.12.5; API 0.42.1
**[Charm](https://www.curseforge.com/minecraft/mc-mods/charm)** 3.3.3
**[UniversalGraves](https://www.curseforge.com/minecraft/mc-mods/universal-graves)** 1.1.4
**Backslot** 1.2.2

When all 3 mods are installed and any items are present in the back slots, it will get dropped outside of a grave upon dying.

To reproduce:

1. Install all 3 mods and its dependencies; launch the game to generate configs
2. Set "TotemOfPreserving Enabled" = false in charm.toml, otherwise it overrides any grave mod
3. Get into a world, take 2 swords, place them in the back slots and die
4. Get back to the grave to discover that the swords are outside of a grave (if there were no other items in the inventory, the grave will also not be created as if you were carrying no items)

Without Charm installed, items kept in back slots are put in the grave as intended. No other items are affected, you can carry anything else in your inventory and it will get saved in your grave upon death. The bug happens even if everything in charm.toml is set to false.

Originally reported to UnversalGraves [here](https://github.com/Patbox/UniversalGraves/issues/24), but the developer of that mod recommended to report here as well.

Logs: https://gist.github.com/Footage2-Amply-Pounce/aba191bbe03003be816913a265240598

**Comment by Patbox** [comment]
Adding support should be relatively easy, you just need to listen to GravesApi.MODIFY_ITEMS_EVENT and add your items there

**Comment by Patbox** [comment]
Going to bump this issue!

**Comment by Globox1997** [comment]
In the latest update, this [https://github.com/Globox1997/BackSlot/blob/1.18/src/main/java/net/backslot/mixin/EntityMixin.java](https://github.com/Globox1997/BackSlot/blob/1.18/src/main/java/net/backslot/mixin/EntityMixin.java) got added (by elbakramer) which might make it compatible with gravestones mod

**Comment by Patbox** [comment]
I'm getting items directly from inventory, so it won't work

**Comment by Globox1997** [comment]
Tested it and fixed with latest update
