### ISSUE TITLE
Packet Processing Error when on multiplayer server

### ISSUE THREAD

**Issue by desarko** [Globox1997/BackSlot#41]
whenever trying to put something on your back while on multiplayer, as soon as you attempt to put an item on your back (sword in the sword slot) you will be instantly kicked and given the reason "Packet Processing Error"

I can confirm that it works in single player.

I have the 1.18 versions of backslot, backslotaddon, fabric api and cloth installed on the server and client.

**Comment by Globox1997** [comment]
hey desarko,
tried to recreate this bug but for some reason I don't get this error.
Do you have java 17, latest backslot and addon, fabric api and cloth config api installed?

**Comment by desarko** [comment]
Hi,
I can confirm that I have all those things. to help narrow down things i've removed the addon for now.

I feel I should note that this is running off a dedicated host, which has paper and bukkit installed on it by default. And this problem can only be created by manually placing the item in the inventory slot, nothing happens if I try to use the keybind.

I also get an error code:

*Error whilst processing packet net.minecraft.network.protocol.game.PacketPlayInWindowClick@29240d6a for Desarkro*

**Comment by desarko** [comment]
Hi, i've been messing around with this problem a bit more and it seems to be a problem with trinkets rather than backslot. I just didn't notice as I always tried to place an item on the trinket slot so assumed it had something to do with this mod.

**Comment by Globox1997** [comment]
You can change the slot positions in the inventory with the config :)

**Comment by Globox1997** [comment]
This should be fixed in a later version.
