### ISSUE TITLE
Emotecraft and Backslot issue

### ISSUE THREAD

**Issue by HEYMANCXN** [Globox1997/BackSlot#42]
I don't know why, when I install backslot and use emotecraft's custom key option, it' won't play animation, but I can open emotecraft's fast-choose wheel to play animation,so I think backslot is block emotecraft's key?

**Comment by HEYMANCXN** [comment]
ps. the version I use is backslot-1.2.2 and emotecraft-for-MC1.17.1-2.0.9-fabric

**Comment by Globox1997** [comment]
Maybe the key has to get changed or you have to install amecs mod

**Comment by HEYMANCXN** [comment]
They use different keys, so I think it’s not a key conflict

**Comment by Globox1997** [comment]
Mh I have no clue to be honest how this happens

**Comment by Globox1997** [comment]
Reopen this issue if still persistent on the latest version.
