### ISSUE TITLE
Unable to see other people weapons/tools on back in multiplayer

### ISSUE THREAD

**Issue by pvtck** [Globox1997/BackSlot#43]
When playing on a server, I can see the tools on my back and my friends can see there’s on there back but not on each other’s. Mod is installed both on client side and on the server

**Comment by Globox1997** [comment]
Mh can't reproduce this bug. Which mod version do you use?

**Comment by pvtck** [comment]
Figured this out too thankyou !

**Comment by woalk** [comment]
@pvtck How did you solve it? I'm running into the same issue.
