### ISSUE TITLE
Belt slot keybind forces me to use shift as well

### ISSUE THREAD

**Issue by zderApfel** [Globox1997/BackSlot#45]
On the latest version of the mod, it forces me to use Shift + whatever key I assign it to, this wasn't an issue on previous versions and there's no conflict with the key I'm trying to use.

**Comment by Globox1997** [comment]
Please install amecs separately and try again

**Comment by Globox1997** [comment]
Reference #12

**Comment by zderApfel** [comment]
I have amecs installed already
