### ISSUE TITLE
Crossbow in backslot bug

### ISSUE THREAD

**Issue by Heamaci** [Globox1997/BackSlot#47]
![2021-12-16_12 03 29](https://user-images.githubusercontent.com/67716228/146441658-bf88c1aa-3445-49a2-a105-005bb84a8e11.png)

for some reason charged crossbows become massive when you put them in your backslot

**Comment by Globox1997** [comment]
Which mod version and mc version is this?

**Comment by Heamaci** [comment]
> Which mod version and mc version is this?

The latest version on 1.18, but previous versions also had this glitch for me

**Comment by Globox1997** [comment]
I can only reference bug #6 here, might give you some info

**Comment by Heamaci** [comment]
> I can only reference bug #6 here, might give you some info

I found out it was the vanilla tweaks resource pack that does this, have no idea why, but removing it fixes this. thanks
