### ISSUE TITLE
Packet Processing Error 

### ISSUE THREAD

**Issue by Thrumptus** [Globox1997/BackSlot#48]
Whenever equipping to a back slot in multiplayer, the server kicks me with the error message "Packet Processing Error"
Mod Version: 1.2.2
Fabric Loader Version: 0.12.10
Minecraft Version: 1.17.1

**Comment by Globox1997** [comment]
I wonder if this happens when only backslot is installed

**Comment by Thrumptus** [comment]
I've tried with and without the addon but it sends the same error either way

**Comment by Globox1997** [comment]
Does it happen when only fabric api, cloth config and backslot is installed?

**Comment by Thrumptus** [comment]
Yep, it also sends the same error if i click on the new slots

**Comment by Globox1997** [comment]
Probably fixed in a later version. Reopen this issue if still persistent on the latest version.
