### ISSUE TITLE
BackSlots started crashing, no clue what's going on [1.18.1]

### ISSUE THREAD

**Issue by SPYROHAWK** [Globox1997/BackSlot#49]
I made a modpack with BackSlots and it was working yesterday, today I think I added some more mods, and then BackSlots started causing a crash. I think I removed all the mods I added (I could be wrong though) but it's still crashing, so idk what's up.

Here is the crash:
[crash-2021-12-23_17.46.28-client.txt](https://github.com/Globox1997/BackSlot/files/7771694/crash-2021-12-23_17.46.28-client.txt)

**Comment by Globox1997** [comment]
Locki mod is incompatible and causes the crash
It has to update its backslot mixin

**Comment by SPYROHAWK** [comment]
Ah, so I was confused about that because I saw it was an issue with the mod "Locki" but it doesn't appear in my modlist, so I assumed I was reading the crash wrong.

Apparently it's embedded into Requiem.

**Comment by Globox1997** [comment]
I can not fix this due to Lokis incompatibility.
