### ISSUE TITLE
Add a way to mimic the Back Tools behavior

### ISSUE THREAD

**Issue by Leeo97one** [Globox1997/BackSlot#5]
It would be cool if we could configure BackSlot to behave like the [Back Tools mod](https://www.curseforge.com/minecraft/mc-mods/back-tools).

**Comment by Globox1997** [comment]
First request of this kind but I have to say that it has intentionally a different mechanic to the Back Tools mod and I have no plans to change it. You could ask the creator of this mod to port his mod :)
