### ISSUE TITLE
Backslot does not display correctly in 1.18.1 latest ver

### ISSUE THREAD

**Issue by Alkiasan** [Globox1997/BackSlot#51]
When using Backslot in 1.18.1, sheathed swords do not display correctly, for some reason, if a sword is in your inventory at all after leaving your mainhand, it will ALWAYS display on your hip. Even if the config option for it is disabled. This leads to even weirder issues if you equip the blade to your hip slot or your back slot. (As seen in image equipping to hip slot) 
![image](https://user-images.githubusercontent.com/62717881/147487486-0d2b5dde-f03f-4ea7-9491-6f4adb030a36.png)
As far as I can tell, there's no console errors, The only mods I have that touch the playermodel are Emotecraft and Figura. This issue did not occur in1.17, seems to be 1.18 exclusive.

**Comment by Alkiasan** [comment]
Other things:

Switching Beltslot side only switches one of the swords' sides

Simply having the sword in your inventory will not cause the issue. The issue itself only starts once you've held the sword in your mainhand at least once.

**Comment by EchoOfThePlanes** [comment]
I just downloaded the mod today, and I am experiencing the exact same problems. I cannot see any console errors, and I have tried creating a new world without any other mods enabled aside from BackSlot, yet the issue persists.

**Comment by Alkiasan** [comment]
Changing into and back out of spectator also seems to get rid of the "Phantom" blade.

**Comment by Globox1997** [comment]
Does it happen in singleplayer?
And if you only fabric api, cloth config and backslot is installed it happens right?
Tried to reproduce this but haven't had success

**Comment by Alkiasan** [comment]
It does happen in singleplayer, strange how you can't reproduce it.

**Comment by Alkiasan** [comment]
After further investiation my issue seems to just be NotEnoughAnimations adding Scabbard swords as an animation in the latest ver. Can't speak for the other person, though.

**Comment by Globox1997** [comment]
Yea I see, not enough animations has a similar renderer here: [https://github.com/tr7zw/NotEnoughAnimations/blob/1.18/NEAShared/src/main/java/dev/tr7zw/notenoughanimations/mixins/PlayerRendererMixin.java](https://github.com/tr7zw/NotEnoughAnimations/blob/1.18/NEAShared/src/main/java/dev/tr7zw/notenoughanimations/mixins/PlayerRendererMixin.java)

**Comment by ThatCarrot** [comment]
Having the same issue.
Is there a fix?

**Comment by Alkiasan** [comment]
> Having the same issue. Is there a fix?

Are you using NotEnoughAnimations? In which case you can disable it in NEA's config.

**Comment by tr7zw** [comment]
This issue can be closed since it's not a bug from BackSlot's side.
