### ISSUE TITLE
Crash when hitting a zombie

### ISSUE THREAD

**Issue by Lordbaane** [Globox1997/BackSlot#52]
https://bytebin.lucko.me/NCvASg5Bpw
First time this happened, but I just switched around resource packs before playing. Also updated 7 mods: 
Amethyst Equipment, Emerald Equipment,  Obsidian Equipment, Alaska Native craft, Copper Equipment, MC Dungeon Armors, and Weapons. Now crashes when I try to open the equipment screen.

**Comment by Lordbaane** [comment]
Disabled Amethyst Eq, Emerald Eq, Obsidian Eq, and Copper Eq., still crashes. Disabled Alaska Native Craft, no change.
Disabled MC D Weapons, crash stopped. Reverted to older version, and sent an issue to MC as well.

**Comment by Globox1997** [comment]
Should be the same as #53
