### ISSUE TITLE
Crash with MCDW and Backslot after MCDW Refactor

### ISSUE THREAD

**Issue by chronosacaria** [Globox1997/BackSlot#53]
Now that I redid the registry, it would appear that the compatibility that our mods had is now broken :(

I have attached the crashlog and if you need any information from me, just let me know

[crash-2022-01-01_15.48.06-client.txt](https://github.com/Globox1997/BackSlot/files/7798216/crash-2022-01-01_15.48.06-client.txt)

**Comment by Globox1997** [comment]
How can I get the soul daggers as items? Like this?
![image](https://user-images.githubusercontent.com/55102939/147874459-bf1ce436-36ff-419c-a0c5-0f369da49c56.png)

**Comment by chronosacaria** [comment]
> How can I get the soul daggers as items? Like this? ![image](https://user-images.githubusercontent.com/55102939/147874459-bf1ce436-36ff-419c-a0c5-0f369da49c56.png)

You should be able to get it the following way:

`ItemsInit.soulDaggerItems.get(SoulDaggersID.DAGGER_ETERNAL_KNIFE)` for the Eternal Knife and `ItemsInit.soulDaggerItems.get(SoulDaggersID.SWORD_TRUTHSEEKER)` for the Truthseeker

**Comment by Globox1997** [comment]
Alright thanks, then it should be fixed with [https://github.com/Globox1997/BackSlot/commit/26603ea6a11a357ee9c2e07d06e5621ca1ba65f7](https://github.com/Globox1997/BackSlot/commit/26603ea6a11a357ee9c2e07d06e5621ca1ba65f7)
