### ISSUE TITLE
Crashing with MC Dungeons Mod

### ISSUE THREAD

**Issue by Neocentric** [Globox1997/BackSlot#54]
I get a crash when using this with MC Dungeons mod. 
[crash-2022-01-04_23.18.04-client.txt](https://github.com/Globox1997/BackSlot/files/7811982/crash-2022-01-04_23.18.04-client.txt)

**Comment by Shockks** [comment]
same crash with MC Dungeons mod

**Comment by Globox1997** [comment]
Update to the latest mcdw version (4.0.1) :)
