### ISSUE TITLE
Feature suggestion for greater customization

### ISSUE THREAD

**Issue by basmens** [Globox1997/BackSlot#55]
A feature suggestion for the config file to allow more customization of the mod. It would be cool if the config file allows for the user to decide what items can go in the back slot.

For example, I have made my own item (kinda) using minecrafts CustomModelData tag and it would be cool if that item could be placed on the back slot. However, the parent item is a chicken_spawn_egg.

The way I'd be able to do this is to go to the config file and add the chicken_spawn_egg to the list
{
    "back_slot_items": [
        "iron_sword",            <--- some items that can already go in the back slot
        "shield",
        "diamond_axe",
        "chicken_spawn_egg"        <--- added myself
    ],
    <other config file data>
}

This would also allow for great customization for modpacks and would fix a lot of compatibility issues with other mods.

**Comment by ThatCarrot** [comment]
has this feature been added? 
I was about to post this very suggestion but noticed it's already been done. I'm thinking of a blacklist / whitelist system, through something like Cloth Config

**Comment by Prodicalx** [comment]
Something like this could be great for a lot of things, even modded weapons

**Comment by Azarilh** [comment]
Was searching for this. It's weird that it's not possible to put the shield in one of the slots.
EDIT: Ok so, it's possible to put the shield in one of the slots, but it either puts it in the main hand, or it puts in the off hand but can't swap back to the belt. :/

**Comment by Globox1997** [comment]
![image](https://user-images.githubusercontent.com/55102939/186109837-f248efa5-f439-47d3-b746-a738aa8e4c4b.png)
You can add items to those tags via a datapack. By changing the head renderer of item models you can edit the size and placement of items so everything is configureable now
