### ISSUE TITLE
Graphical Issue with Trinkets

### ISSUE THREAD

**Issue by RotokEralil** [Globox1997/BackSlot#56]
When using Trinkets (in particular in the trinket slot and ring slot) The inventory graphics are overlaid. They still exist in those slots, (back, belt, trinket, ring) and nothing is lost, but the graphics are overlaid.
![With rings and words](https://user-images.githubusercontent.com/96855797/148456140-816d53ed-da7a-4246-af47-edcf01af8dd8.PNG)
![Without rings and swords](https://user-images.githubusercontent.com/96855797/148456141-a75d4c02-9421-4cfc-9d18-8f4ca4fced1f.PNG)
.

**Comment by Globox1997** [comment]
Turn on the slot change setting in the config :)

**Comment by RotokEralil** [comment]
Huzzah! Now I just need to find a way to move my inventory sort button a little higher so it doesn't overlap the new placement lol

**Comment by Globox1997** [comment]
You can even place the slots where you want them to be with the advanced settings, position x and y :)

**Comment by RotokEralil** [comment]
<3
