### ISSUE TITLE
[1.18.1] Adding items to backslot via datapack and item scaling

### ISSUE THREAD

**Issue by lizfinite** [Globox1997/BackSlot#57]
This is more of a feature request than a bug, but after adding SurvivalPlus's lightsabers in my mod pack to belt slots via a datapack, I noticed that for certain items the scale can be quite off. However adjusting the scaling options present in the mod config obviously apply to all items so you either have to make the trade off for small swords or big lightsabers. 

Default Scaling (2.0):
![2022-01-11_18 15 04](https://user-images.githubusercontent.com/36245622/149041557-5e04e1ee-7c99-409c-87cd-a6daad055f78.png)
![2022-01-11_18 15 07](https://user-images.githubusercontent.com/36245622/149041560-725c7f2c-3365-4eeb-bf00-34b890267b53.png)
1.0 Scaling:
![2022-01-11_18 15 30](https://user-images.githubusercontent.com/36245622/149041561-9f331b45-821c-4c54-bc1a-db60635342e5.png)
![2022-01-11_18 15 39](https://user-images.githubusercontent.com/36245622/149041563-4e65a079-a7a0-4094-a3d0-e4966440ac2c.png)

Is there a way to resize items beltslot/backslot via the datapack? If not, it would be nice to be able to do so. However that might also be asking quite a lot/the impossible for what datapacks can do. 

So then, would it be possible to compensate with a resourcepack somehow? By changing the json of the model? I know you can scale it up in the hand vs on the ground or in an item slot, but I'm not sure how this one scales since the saber is different in all those situations from the size it is on my belt currently. 

Thanks for exposing it to data to make it work for adding additional items though, that's already really neat :smile:

**Comment by Globox1997** [comment]
I guess we can close this issue with your PR #62 as a reference :D thanks again!
