### ISSUE TITLE
compatiblity with hardcore torches

### ISSUE THREAD

**Issue by Heamaci** [Globox1997/BackSlot#58]
could there be compatibility with hardcore torches? It adds unlit and lit lanterns, but they can't be put in your belt slot.
So, you get dynamic lighting when it is lit and when it runs out of fuel, it will no longer emit light but still be equipped.

https://www.curseforge.com/minecraft/mc-mods/hardcore-torches

**Comment by Globox1997** [comment]
Reference [https://github.com/Globox1997/BackSlotAddon/issues/6](https://github.com/Globox1997/BackSlotAddon/issues/6)
