### ISSUE TITLE
Double tools & weapons appearing on beltslot w/ "BackSlot" + "Not Enough Animations" installed

### ISSUE THREAD

**Issue by takeovercomet** [Globox1997/BackSlot#59]
Hey there! I came across a strange incompatibility today with the mod "[Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)"

With both the "[Back Slot](https://www.curseforge.com/minecraft/mc-mods/backslot)" and "[Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)" mods enabled you will encounter a bug where when you have a weapon or tool in your hotbar (not added to your Back or Belt slots)... upon switching to a different slot in your hotbar it will appear as though your tool or weapon has been added to the belt slot. When you actually equip that tool or weapon to the beltslot, it will make it look like there are two of those weapons/tools in the beltslot. If you try equiping the tool/weapon to your backslot instead, it will still show that same tool/weapon in your belslot in addition to being on your backslot.

I figured it was worth making a note of the issue here for anyone else who might be experiencing this issue. I've resolved this for myself by giving up the "[Not Enough Animations](https://www.curseforge.com/minecraft/mc-mods/not-enough-animations)" mod in my modlist seeing as the "[Back Slot](https://www.curseforge.com/minecraft/mc-mods/backslot)" mod is more functionally useful, but if compatibility between these two mods was possible, that would of course be awesome.

**Comment by OarisHunter** [comment]
This is easily solved by setting both "showLastUsedSword" and "showLastUsedToolsOnBack" to false in the not enough animations config
