### ISSUE TITLE
Crossbow Bug

### ISSUE THREAD

**Issue by MisterRickiy** [Globox1997/BackSlot#6]
Can you Fix it?
![2020-12-04_12 54 51](https://user-images.githubusercontent.com/54863675/101161041-42ae9580-3630-11eb-8985-55afa6d160f4.png)

**Comment by Globox1997** [comment]
Is this crossbow the vanilla bow?

**Comment by MisterRickiy** [comment]
Yes exactly!

**Comment by Globox1997** [comment]
Can't reproduce this bug :/

**Comment by MisterRickiy** [comment]
Ok maybe the mod has some incompatibilities with my other mods.

**Comment by Globox1997** [comment]
I guess so, could you send a mod list?

**Comment by MisterRickiy** [comment]
Yes I can. Can you wait a little time?

**Comment by MisterRickiy** [comment]
![Modlist](https://user-images.githubusercontent.com/54863675/101278854-7cada200-37be-11eb-98e8-856be3006792.png)

**Comment by Globox1997** [comment]
mh I don't know which mod could lead to this bug

**Comment by Globox1997** [comment]
The only way is figure out which mod causes trouble but I don't have time to test every single one

**Comment by Globox1997** [comment]
May the bug caused by the shader you are using?

**Comment by MisterRickiy** [comment]
sorry that I haven't answered in a long time.  The bug no longer occurs with me is definitely due to a resource pack.  many thanks

**Comment by Globox1997** [comment]
oh great to hear :) be blessed
