### ISSUE TITLE
Inventory Backpack compatibility issue

### ISSUE THREAD

**Issue by ShainCasterway** [Globox1997/BackSlot#61]
Hello Globox1997
I found a compatibility issue with Inventory Backpack https://www.curseforge.com/minecraft/mc-mods/inventory-backpack
It makes so that the pants and boots slots cover some slots of the backpack inventory, making them inacessible.
![image](https://user-images.githubusercontent.com/87939914/151080745-e9ff99a1-9cc2-46ce-b87b-90861a8e0748.png)
Is there a possibility for you to fix this issue? 
(maybe unrelated, but the mod Trinket of Undying (Fabric) https://www.curseforge.com/minecraft/mc-mods/trinket-of-undying-fabric also adds a custom slot but i never found UI issues with that mod. Most likely it's the way it's implemented, so maybe have a look at the source code? I really hope i'm not coming out as mean or anything, i'm just trying to present what i think it's a possible improvement to your mod)

**Comment by ScoobyVI** [comment]
Does manually entering an offset for the slots help with this issue?

**Comment by Globox1997** [comment]
Try as @ScoobyVI mentioned. Otherwise I have no plans to add compatibility to Inventory Backpack. Ask their dev for compat.
