### ISSUE TITLE
Bow big?

### ISSUE THREAD

**Issue by 1nickoman1** [Globox1997/BackSlot#64]
![image](https://user-images.githubusercontent.com/74034273/153781969-3aa28c68-c9f6-4039-8011-b4d5c934b3b1.png)

Uh is this suppose to happen to the bow? because it looks really big and i thought it was the backslots addon but it wasnt so im kinda confused

**Comment by Ozakinn** [comment]
got this same issue but with MCDW mod.
i had to revert back to 1.2.4 version

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/BackSlot/commit/5608a73f10b727d9259b219c0f5a6ce4ecd6326c](https://github.com/Globox1997/BackSlot/commit/5608a73f10b727d9259b219c0f5a6ce4ecd6326c)
