### ISSUE TITLE
I have no idea on how to move my backslot next to the book

### ISSUE THREAD

**Issue by mehdicool** [Globox1997/BackSlot#65]
I have been searching for the next 30 minutes and I havn't seen any config menu , I am using the trinkets mod and while searching I have seen things  like use the config to change the place of the slots but **_WHERE IS THE CONFIG?_** 
![image](https://user-images.githubusercontent.com/38765622/155395951-4f54da32-1148-4035-8510-b0d6a08ba88f.png)

**Comment by mehdicool** [comment]
so by config you litterally meant the file config... well I wouldn't call that user friendly...

**Comment by Globox1997** [comment]
Glad you found it :) With modmenu you can access the config while in game (for this setting you have to restart the client tho)
