### ISSUE TITLE
Giant Items

### ISSUE THREAD

**Issue by ShotCosine** [Globox1997/BackSlot#66]
Hello, I am making a resourcepack that adds 3D features to swords using blockbench. I'm experiencing the "giant crossbow" issue here:
![Screenshot (11)](https://user-images.githubusercontent.com/50850656/156271014-795a901b-04a4-4b79-b12d-ba3f7150013e.png)
I'm just confused on what value I need to edit to make the sword the normal size on the backslot again. The sword is default size in hand, item frame, armor stand, and on the ground. What value in the model json does the mod read to determine how big the item should be?

**Comment by Globox1997** [comment]
In the latest version it uses the head variant :)

**Comment by Globox1997** [comment]
So basically you can edit the position and size with a resource pack.
Just edit the head variant of the model
