### ISSUE TITLE
floating too big bow

### ISSUE THREAD

**Issue by ChocoMartini** [Globox1997/BackSlot#67]
![2022-03-10_20 20 15](https://user-images.githubusercontent.com/86866560/157670534-822ea6ed-3a42-4d86-bf59-6eefced9a3dd.png)
Bow is too big and misplaced when compare to other items
(both of them have the default config)
![2022-03-10_20 20 30](https://user-images.githubusercontent.com/86866560/157670679-42e473eb-e86c-42d8-8133-3e22e13a4bca.png)

**Comment by cowsha** [comment]
Same here, bows from mods seems to work alright.
![2022-03-12_12 23 43](https://user-images.githubusercontent.com/35926994/158005080-d906ed4d-b1da-473d-85d9-83eb1b50c48d.png)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/BackSlot/commit/5608a73f10b727d9259b219c0f5a6ce4ecd6326c](https://github.com/Globox1997/BackSlot/commit/5608a73f10b727d9259b219c0f5a6ce4ecd6326c)
Thanks for reporting

**Comment by VoidLock92** [comment]
![image](https://github.com/user-attachments/assets/44696ce4-5572-43de-992d-d90195edb2d4)
Strange same issue.
