### ISSUE TITLE
Trinkets Compatibility (Idea)

### ISSUE THREAD

**Issue by NattyNuke** [Globox1997/BackSlot#7]
I've noticed that this amazing mod conflicts with the trinkets mods. 

This is what it looks like with my modpack installed.
![ModpackWithoutBackslots](https://user-images.githubusercontent.com/73963232/102716257-b4c9e000-42a8-11eb-81f2-394bf56eeed7.png)

This is what it looks like with my modpack and Backslots installed.
![ModpackWithBackslots](https://user-images.githubusercontent.com/73963232/102716266-c6ab8300-42a8-11eb-8566-c3a6f9c388d4.png)

This is what I am imagining the fix to look like.
![What I Imagine it would look like](https://user-images.githubusercontent.com/73963232/102716281-e04cca80-42a8-11eb-8860-a18471a871ae.PNG)

I understand the absurdity of asking this, as I'm pretty sure that modding isn't just some walk in the park. Maybe there could be an option to turn on trinket compatibility in the config?

Here's my mod list just in case it is needed.
![ModlistPart1](https://user-images.githubusercontent.com/73963232/102716326-33268200-42a9-11eb-896e-940c5dba0edf.JPG)
![ModlistPart2](https://user-images.githubusercontent.com/73963232/102716328-3457af00-42a9-11eb-965f-64ab5303e992.JPG)

**Comment by Globox1997** [comment]
There was actually a version of backslot which automatically moved the slots upwards when trinkets was installed but I removed it and added the a config option to put the extra slots next to the recipe book.
There is another trinkets based mod which adds one more slot above your hand looking slot which made backslot not compatible with the slots above the second hand slot which is the reason for the new system

**Comment by NattyNuke** [comment]
Ahh okay! Sorry, I didn't know what that config option did, turns out I had to reset my computer for it to take effect. Thanks for letting me know!
