### ISSUE TITLE
Weird visual bug. [bug]

### ISSUE THREAD

**Issue by SebastianDevus** [Globox1997/BackSlot#73]
Currently using sodium, on linux.
![2022-04-03_10 00 24](https://user-images.githubusercontent.com/86898507/161430748-6f3c85bf-4c76-4334-a739-e55e489628bb.png)
![2022-04-03_10 00 27](https://user-images.githubusercontent.com/86898507/161430753-302cb424-cd10-4249-8edc-2816d26a72a0.png)

**Comment by asa-kern** [comment]
also have this, also using sodium, on Arch Linux

**Comment by Globox1997** [comment]
Does this happen when only backslot and its dependencies is installed?

**Comment by DuckXGG** [comment]
It appears to only happen when you use sodium. But it would be really nice if it worked with sodium

**Comment by Globox1997** [comment]
This happens when you use a resource pack which edits the head renderer of item models
