### ISSUE TITLE
Not Working Right with Pirates Life Mod

### ISSUE THREAD

**Issue by NealSavage** [Globox1997/BackSlot#74]
![image](https://user-images.githubusercontent.com/4138801/164954336-5075ac4c-5f75-4ce7-809d-fb67814d7373.png)

Kind of clear the that the musket doesn't work great. lol The other slot just sent it to the inventory instead of my hot bar.

**Comment by Globox1997** [comment]
You might be able to fix this by editing the head renderer of the item model

**Comment by Globox1997** [comment]
Reference [https://github.com/Globox1997/BackSlot/issues/80](https://github.com/Globox1997/BackSlot/issues/80)
