### ISSUE TITLE
Backpack mods incompatibility

### ISSUE THREAD

**Issue by Kratos-Lee520** [Globox1997/BackSlot#78]
I'm just going to paste the comment from curseforge here: 

I normally use forgotten graves on fabric but I have used others and never saw that any of them actually keep the backslots items, they're just deleted. I have used [Forgotten Graves](https://www.curseforge.com/minecraft/mc-mods/forgotten-graves) and [You're in Grave Danger](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger). I haven't used the second one since maybe 1.16.5 so there may have been an update to make it compatible, but I don't really know how to check for features released after a specific version other than clicking through every update the mod's had since then. Hopefully this can be fixed your side so I don't have to message a few backpack mod developers and try to get one to make it compatible with the backslot  mods. Thank you for your help!

And I might've also used [Corail Tombstone](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone) at one point but not sure if it was with these mods.

Also same with Backslot addon. Gravestone mods don't keep items in that slot either

**Comment by Rubinian** [comment]
You're in grave danger has compatability with backslot, except for when BackSlots "lifesaver"-function activates because of other mods, as mentioned in #84 for example.

**Comment by Globox1997** [comment]
Should be compatible with the latest version.
Basically this provides the info
![image](https://user-images.githubusercontent.com/55102939/186108792-e2d325ae-f0d1-4d83-9309-400e99980eef.png)
