### ISSUE TITLE
item highlight is under back slot

### ISSUE THREAD

**Issue by RyanCR03** [Globox1997/BackSlot#8]
the white overlay that happens when selecting an item shows under the icon for the back slot and over the belt slot when it's supposed to be over both.

**Comment by Globox1997** [comment]
will leave it open until I add those slots :) thanks for info

**Comment by Globox1997** [comment]
definitely a cosmetic issue, found the weird problem but can't fix it right now.

**Comment by Globox1997** [comment]
fixed with [https://github.com/Globox1997/BackSlot/commit/1bd8a7a37e3c6aae125ea5f301fc3d8fe6f35f38](https://github.com/Globox1997/BackSlot/commit/1bd8a7a37e3c6aae125ea5f301fc3d8fe6f35f38) and another commit :)
