### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by ghost** [Globox1997/BackSlot#80]
[Deleted]

**Comment by Globox1997** [comment]
Check your resource packs :)
Backslot uses the head model of items which a resource pack shouldn't touch cause it is never used.
Have to make that info public anywhere

**Comment by inflorescence91838** [comment]
I'm guessing I should delete the contents of assets/minecraft/models/item ?

**Comment by Globox1997** [comment]
no need to delete the whole folder, just remove the head part inside the model files

**Comment by Azarilh** [comment]
Problem is that i use a resource pack to remove the stitching issue with weapons and tools. It's an eye sore without the resource pack. :/

**Comment by VybeX** [comment]
![2022-08-05_18 11 08](https://user-images.githubusercontent.com/91761291/183218184-09c43287-9f18-4d68-b55e-470dedd40714.png)
![2022-08-05_18 11 25](https://user-images.githubusercontent.com/91761291/183218194-b19cddda-3b0e-42b9-be97-26a570e2f249.png)

Beltslot renders shears and flint and steel like this. i'm not sure what's going on. i uninstalled all mods and even deleted my .minecraft folder. re-installed fabric, iris and sodium and this **still** happens in game.

Current mods:

Backslot
Backslot Add On
Cloth Config

**Comment by Globox1997** [comment]
This happens due to a resource pack.
BackSlot renders items with the head item renderer but with 1.19.2 I changed some settings, that might help.

**Comment by fesheath** [comment]
I dont have any resourcepacks, how do I fix this?

**Comment by Skeithh** [comment]
Also running into this issue with no resource pack active on the 1.2.6 version for 1.18.2. In addition our resource pack does not deal with head models at all so that'd be strange.

**Comment by Skeithh** [comment]
Made the realisation that this bug occurs not with every item. It seems like regular tools (swords,pickaxes,axes,etc) render correct on the belt slot but things like shears do not.

**Comment by fesheath** [comment]
So it happens on versions prior to 1.19 too, how does one fix this?

**Comment by Globox1997** [comment]
Again this only happens with resource pack changing the head render model of items.
Mods can include resource packs which can not get disabled but always overwritten.
It looks like this 
![image](https://user-images.githubusercontent.com/55102939/189050876-99cca984-b335-4b2b-8a9e-4b340b9b6706.png)
Remove it and everything will work fine

**Comment by Alex134831** [comment]
@Globox199 nope, it seems to happen without any resourcepacks and other mods too.

```
Loading Minecraft 1.19 with Fabric Loader 0.14.9
- backslot 1.2.8
- backslotaddon 1.0.9
- cloth-config 8.2.88
- fabric 0.58.0+1.19
- java 17
```

This way, bow on back is normal, shear on belt is broken.
![image](https://user-images.githubusercontent.com/31597633/189476618-2f2d76aa-b501-4015-a7bd-860f92d95aa4.png)

This way, both are broken.
![image](https://user-images.githubusercontent.com/31597633/189476632-16322b89-5650-48f7-b7eb-c8dc8d465afc.png)

**Comment by Globox1997** [comment]
Positioning, translation and scaling can get modified by a resource pack. Check out the Readme for info.
