### ISSUE TITLE
Can no longer add items to backslots after installing trinkets

### ISSUE THREAD

**Issue by vampirebats** [Globox1997/BackSlot#81]
Hi,

Before installing trinkets, I tested the mod and it worked as intended. The slots are still there, I just can't add any items to them. When I click the slot to add the item, it appears briefly on my back or side, then unequips suddenly. I know it's a trinkets issue, but I can't uninstall trinkets unfortunately because another mod needs it to work :( 

I love backslots and I don't want to uninstall it, so if anyone knows of a fix please let me know!

**Comment by Globox1997** [comment]
check out the config settings, that might help you
