### ISSUE TITLE
[Feature Request] Backslot OnHover Shows Beltslot

### ISSUE THREAD

**Issue by cymophic** [Globox1997/BackSlot#83]
For mod compatibility, instead of putting it under the crafting grid, maybe you can put the belt slot **under** the back slot and only show it when you hover over the back slot. Just like how it multiple slots work in the _[Artifacts](https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric)_ mod

![image](https://user-images.githubusercontent.com/97153344/183295735-de615a14-7724-4b75-9da0-96c6465f4bf3.png)
Pic for reference

**Comment by Globox1997** [comment]
Somebody could write an addon for this behavior but my mod doesn't depend on trinkets mod.

**Comment by Globox1997** [comment]
Reference this [https://github.com/Globox1997/BackSlot/issues/71](https://github.com/Globox1997/BackSlot/issues/71)
