### ISSUE TITLE
[Feature request][Compatability Issue] Making the "livesaver" drop configurable to ensure compatability

### ISSUE THREAD

**Issue by Rubinian** [Globox1997/BackSlot#84]
The mod yigd (https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger/files/3926910) is compatible with BackSlot, unless Charm (https://www.curseforge.com/minecraft/mc-mods/charm/files/3921260) is also installed; in this case, even when the TotemOfPreserving module is disabled, the items in the backslots will drop and not be in the grave. According to the author of yigd, this happens because of the "lifesaver" drop dropping these items when Charm is present. Could you make this "livesaver" drop able to be disabled in the config?

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by Rubinian** [comment]
This one: [https://www.curseforge.com/minecraft/mc-mods/backslot/files/3686502](https://www.curseforge.com/minecraft/mc-mods/backslot/files/3686502)

**Comment by Globox1997** [comment]
This should be partly fixed with a later update, items get dropped rather than deleted on death.
