### ISSUE TITLE
The inventory slots are not positioned correctly with Trinkets mod installed

### ISSUE THREAD

**Issue by jeremyriveradev** [Globox1997/BackSlot#85]
The inventory slots Xpos are misaligned to the items by 77px. 
Not the items but the slots themselves, the items are correctly positioned. The items are not positioned over the slots.

This is a screenshot, https://ibb.co/BZC0Zpn, with these offsets set
Backslot X : 0 , Backslot Y : -39
Beltslot X : 0 , Beltslot Y : -18
Here you can see the items are pushed up by the correct amount, but the slots Xpos are offset by 77px even though the Xpos is not changed.
I tested changing the X to -77px, and it perfectly aligns the slots, but the items get pushed that same offset since the slots are not aligned to the items.

**Comment by SplendidAlakey** [comment]
Are you using Better Recipe Book and its feature to keep the inventory always centered? If yes, that's why.

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by Globox1997** [comment]
Fixed it with the latest update
