### ISSUE TITLE
[Bug] Belt Slot broken in 1.19

### ISSUE THREAD

**Issue by Pandasaurus-Rex** [Globox1997/BackSlot#88]
I'm running the latest version of backslot (1.2.8) and ever since updating from 1.18.2 to 1.19 the belt slot no longer works as intended. The keybind doesn't work to draw/stow items, so I can add a sword/tool/etc to the belt slot in the inventory gui, but I have no way to access it because nothing happens when I hit the belt slot switch key. And it's not a keybind conflict issue, I changed the belt slot switch to a key that has no other keybinds associated with it and it still doesn't work. The back slot, on the other hand, does work as intended, if that helps narrow the issue at all.

**Comment by Globox1997** [comment]
Did you try to install amecs and check if this is still an issue with it?

**Comment by Globox1997** [comment]
Reopen with further information
