### ISSUE TITLE
Draw slots relative to inventory and not the entire screen

### ISSUE THREAD

**Issue by Cynosphere** [Globox1997/BackSlot#89]
https://github.com/Globox1997/BackSlot/blob/e62c4e0ea283b1270b8a3845979ef4e5d70af927/src/main/java/net/backslot/mixin/client/InventoryScreenMixin.java#L51-L57

This can be simplified by using `this.x` and `this.y`

There is also `RecipeBookWidget.findLeftEdge` so you don't have to hardcode and assume nothing will modify the position of the recipe book.

Slots will break with both Better Recipe Book and Scout (https://github.com/Cynosphere-mc/Scout/issues/20) due to the recipe book position being hardcoded.

**Comment by Globox1997** [comment]
Changed with [https://github.com/Globox1997/BackSlot/commit/794e1d5ca5b2aeb9d3c1aaba42ef34666ae0c580](https://github.com/Globox1997/BackSlot/commit/794e1d5ca5b2aeb9d3c1aaba42ef34666ae0c580)
