### ISSUE TITLE
Simply swords error

### ISSUE THREAD

**Issue by Developer2704** [Globox1997/BackSlot#90]
Simply swords weapons float and are too large. The weapons also pass through the player model.

![2022-09-01_17 09 31 - Copy](https://user-images.githubusercontent.com/111246017/188032726-c81e9bbf-f762-4354-8a40-3e886f8b3368.png)

**Comment by Globox1997** [comment]
Check out your resource pack. BackSlot uses the head render model of each item

**Comment by Developer2704** [comment]
No the only pack I am using changes armor

**Comment by Globox1997** [comment]
So it is an own mod? then the mod author changed the head model renderer but you can fix that via a resource pack

**Comment by Developer2704** [comment]
can you make one

**Comment by Sweenus** [comment]
This is fixed in the latest release of Simply Swords

**Comment by Globox1997** [comment]
I guess then it can get closed :)
