### ISSUE TITLE
Setting the Backslot Y to be above the beltslot causes a graphical issue.

### ISSUE THREAD

**Issue by Coffe-e** [Globox1997/BackSlot#92]
It's hard to describe, so here's what i'm talking about so I included some images, but essentially the background of the inventory slots gets shoved upwards, and it doesn't happen if i raise both slots by -18, only when i set the backslot to -36.
(I couldn't upload images at the time of writing this, so I had to post them to an Imgur. Sorry!)
https://imgur.com/a/NoHCyP7

**Comment by Globox1997** [comment]
This should be fixed with a later update. Reopen this issue if still persistent on the latest version.
