### ISSUE TITLE
[Incompatibility] Items from MC Dungeons Weapons render far too small

### ISSUE THREAD

**Issue by JumpStartFartHam** [Globox1997/BackSlot#93]
When you put a weapon or tool from the MC Dungeons Weapons mod in your back slot or belt slot, the model renders far smaller than it does while being held in your hand. This seems to occur for every weapon and tool in the mod that I've tested, but specifically just for ones from that mod, no other vanilla or modded items that I've found so far. I'm including a few screenshots here to help show what I mean.

For reference, this is with BackSlot 1.2.10, MC Dungeons Weapons 5.0.4, and Fabric 0.14.9 for Minecraft 1.19.2.

![2022-10-20_20 27 36](https://user-images.githubusercontent.com/70125767/197090618-693012a5-c256-4b73-90a5-5e59ed02bae0.png)
![2022-10-20_20 28 19](https://user-images.githubusercontent.com/70125767/197090657-05a1261c-f266-4b9d-ac51-afa25f8434af.png)
![2022-10-20_20 26 50](https://user-images.githubusercontent.com/70125767/197090551-792bdc5f-066c-41f6-b920-0198bc4e383a.png)
![2022-10-20_20 27 06](https://user-images.githubusercontent.com/70125767/197090590-bd967003-4a2c-49b9-b8ba-cc368f75a680.png)

**Comment by Globox1997** [comment]
Position and scale can get adjusted with a resource pack, check out the Readme..
