### ISSUE TITLE
Minecraft Dungeons Weapons Items are rendering a little too tiny on the character!

### ISSUE THREAD

**Issue by 444wa** [Globox1997/BackSlot#94]
Used this mod and MC Dungeons Weapons in a 1.18.2 modpack, and they had worked perfectly fine. This is a brand new issue I had never seen before, that only appeared in this 1.19.2 modpack I'm working on, so maybe this is a version issue?
(I don't know that much about mods, please forgive my ignorance)
I'm not sure what is causing this issue, but it was a little surprising to see. I am 100% sure this is not supposed to happen.
I have all the mods required and no other resource pack is above it, or interfering with it. 
![image](https://user-images.githubusercontent.com/104756144/201023960-098686eb-acf1-4134-a682-ce9a5277b00f.png)

**Comment by Globox1997** [comment]
Position and size can get adjusted with a resource pack, check out the readme.
