### ISSUE TITLE
My world unload when press any keybind from the mod with Immersive Portals installed

### ISSUE THREAD

**Issue by Landrozaum** [Globox1997/BackSlot#99]
Minecraft 1.19.2
Fabric 0.14.12
Fabric API 0.72.0
Mod Version 1.2.11.1

Issue: When i am with Immersive Portals installed, and i try press the backslot or the beltslot keybind, my world unloads, and the game go to the main menu screen, i enter in the world and the item goes to the back slot but obviously, everytime the world unloads.

This is what is showed to me:
![javaw_31e2H1hzk2](https://user-images.githubusercontent.com/76543480/212806870-6272d360-2403-4faf-a787-0f40ca5e6981.png)

**Comment by Landrozaum** [comment]
surprised that immersive portals itself takes the blame away from him, and yes, i tried to play with immersive portals and without and everything goes well

**Comment by qouteall** [comment]
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1323

**Comment by qouteall** [comment]
@Landrozaum 
Immersive Portals is just checking threads and because it seems that backslot is trying to send packet in non-server thread and sending packet in non-server thread is unsafe even without Immersive Portals.

**Comment by qouteall** [comment]
I have to clearify that ImmPtl is just doing thread checking for ease of debugging (it indeed found a thread safety issue of backslot) so it's technically not ImmPtl's fault.

https://github.com/Globox1997/BackSlot/issues/107

**Comment by qouteall** [comment]
The next version of ImmPtl will not make the checking strict to reduce misunderstanding.

**Comment by Globox1997** [comment]
Fixed unsafe handling with [https://github.com/Globox1997/BackSlot/commit/fec26b685f7a9bef92efc12bb66f3ad814a969e4](https://github.com/Globox1997/BackSlot/commit/fec26b685f7a9bef92efc12bb66f3ad814a969e4)
